# Generated by Django 4.0 on 2022-06-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ACTIVITÉS UNASS',
            },
        ),
        migrations.CreateModel(
            name='AnetmentUnass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Anetment Unass',
            },
        ),
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anntenne', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CaralogueFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Caralogue Des Formation',
            },
        ),
        migrations.CreateModel(
            name='ChooseUsReasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ChooseUsReasons',
            },
        ),
        migrations.CreateModel(
            name='MessagesFromNewClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MessagesFromNewClients',
            },
        ),
        migrations.CreateModel(
            name='OurContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='team')),
            ],
            options={
                'verbose_name_plural': 'TeamMember',
            },
        ),
        migrations.CreateModel(
            name='WhyChoosingUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_n1', models.ImageField(upload_to='Why_shoose_us')),
                ('reasons', models.ManyToManyField(to='platforme.ChooseUsReasons')),
            ],
            options={
                'verbose_name_plural': 'WhyChoosingUs',
            },
        ),
        migrations.CreateModel(
            name='UnassActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image_n1', models.ImageField(blank=True, null=True, upload_to='Why_shoose_us')),
                ('image_n2', models.ImageField(blank=True, null=True, upload_to='Why_shoose_us')),
                ('image_n3', models.ImageField(blank=True, null=True, upload_to='Why_shoose_us')),
                ('activites', models.ManyToManyField(to='platforme.Activite')),
            ],
            options={
                'verbose_name_plural': 'ACTIVITÉ',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField(blank=True, null=True)),
                ('toDate', models.DateField(blank=True, null=True)),
                ('message', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('refused', models.BooleanField(default=False)),
                ('cert_dir', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('antenne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforme.antenne')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='présidente', to='user.user', verbose_name='présidente')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formature', to='user.user', verbose_name='formature')),
            ],
        ),
        migrations.CreateModel(
            name='Deplomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('cin', models.CharField(blank=True, max_length=25, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birthPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('formationPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('year_num', models.IntegerField(blank=True, null=True, verbose_name='order in this year')),
                ('serial_num', models.CharField(blank=True, max_length=12, null=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deplomat', to='platforme.formation')),
            ],
            options={
                'ordering': ['date', 'year_num'],
            },
        ),
    ]
