# Generated by Django 4.0 on 2022-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='convention',
            field=models.BooleanField(default=False),
        ),
    ]
