# Generated by Django 4.0 on 2022-06-11 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforme', '0002_formation_convention'),
    ]

    operations = [
        migrations.AddField(
            model_name='anetmentunass',
            name='link',
            field=models.CharField(default='#', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formation',
            name='antenne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platforme.anetmentunass'),
        ),
        migrations.DeleteModel(
            name='Antenne',
        ),
    ]
